### ISSUE TITLE
No Pairing Code

### ISSUE THREAD

**Issue by jclinder67** [Aayush9029/KenobiSite#5]
I bought your applewatch app

The pairing code in the Mac App is looking like a IP address and not a 4 digit code ending with #
What can I do ?

**Comment by Aayush9029** [comment]
You can run this command to get the pairing code.

ifconfig | grep 'inet.*broadcast' | awk '{print $2}' | cut -d. -f4

The code is basically the last numbers of your IP address.

if that command doesn't work for you find your local IP address and use the last number as the code

for example 192.168.2.64 => you'd use 64 as the code.

Seems like I didn't account for "different" local ip

I’ll be accounting for that in the next macOS app release!

**Comment by jclinder67** [comment]
So I have to type 0040 ???

 

It is not working either with the command or 0040

 

De : Aayush ***@***.***>
Répondre à : Aayush9029/KenobiSite ***@***.***>
Date : lundi 22 novembre 2021 à 23:41
À : Aayush9029/KenobiSite ***@***.***>
Cc : JC LINDER ***@***.***>, Author ***@***.***>
Objet : Re: [Aayush9029/KenobiSite] No Pairing Code (Issue #5)

 

You can run this command to get the pairing code.

ifconfig | grep 'inet.*broadcast' | awk '{print $2}' | cut -d. -f4

The code is basically the last numbers of your IP address.

if that command doesn't work for you find your local IP address and use the last number as the code

for example 192.168.2.64 => you'd use 64 as the code.

Seems like I didn't account for "different" local ip

I’ll be accounting for that in the next macOS app release!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aayush9029** [comment]
Follow these steps

1. Open System preferences

2. Click Network
![Screen Shot 2021-11-22 at 6 58 53 PM](https://user-images.githubusercontent.com/43297314/142952598-97af92c1-551e-4577-a9cc-7ccd3143047f.png)
3. Click on advance
![Screen Shot 2021-11-22 at 6 59 26 PM](https://user-images.githubusercontent.com/43297314/142952635-2b964112-61dd-4822-9c1b-e03dc55a1d1c.png)
4. Click on TCP/IP 
![Screen Shot 2021-11-22 at 6 59 48 PM](https://user-images.githubusercontent.com/43297314/142952662-80843011-43ad-4d14-a19e-6e4755962de2.png)

---

![Screen Shot 2021-11-22 at 7 00 15 PM](https://user-images.githubusercontent.com/43297314/142952740-ea37c98d-4d56-4f82-adad-7fc43923939f.png)

As you can see, my local IP address is 192.168.2.**23**

Therefore my pairing code is: **23##**

---

Here are more some examples:

local ip = 192.168.2.167 
The code will be  **167#**


local ip =   10.112.23.195
the code will be **195#**

local ip = 10..14.51.1
the code will be **1###**

----

Mind including the screenshot for the last step?
I'll guide you through this 😄

**Comment by jclinder67** [comment]
First I go to bed now because it is 1:17AM now

Second I did exactly what you show below even before you sent it but the mac is not responding to the control in the watch app even they appear. (I tried nearly all of them)

I have had companies in tech since 1990 so I am quite a PowerUser by the way…

My father gifted me the first mac in 1984 also !

 

Best

 

De : Aayush ***@***.***>
Répondre à : Aayush9029/KenobiSite ***@***.***>
Date : mardi 23 novembre 2021 à 01:08
À : Aayush9029/KenobiSite ***@***.***>
Cc : JC LINDER ***@***.***>, Author ***@***.***>
Objet : Re: [Aayush9029/KenobiSite] No Pairing Code (Issue #5)

 

Follow these steps
Open System preferences
Click Network

Click on advance

Click on TCP/IP
As you can see, my local IP address is 192.168.2.23

Therefore my pairing code is: 23##

Here are more some examples:

local ip = 192.168.2.167
The code will be 167#

local ip = 10.112.23.195
the code will be 195#

local ip = 10..14.51.1
the code will be 1###

Mind including the screenshot for the last step?
I'll guide you through this 😄

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aayush9029** [comment]
I've updated the Mac, it should generate proper code :)
https://github.com/Aayush9029/KenobiSite/releases/download/v1.3/Kenobi.app.zip

**Comment by Aayush9029** [comment]
> I have had companies in tech since 1990 so I am quite a PowerUser by the way…

We love power users like you!
We're working on an opensource desktop app which works on linux and windows as well as macOS, Feel free to check out the free and  open-source app!

https://github.com/Aayush9029/Kenobi-Server

**Comment by jclinder67** [comment]
It is, but still not connecting to the Mac !

 

De : Aayush ***@***.***>
Répondre à : Aayush9029/KenobiSite ***@***.***>
Date : mardi 23 novembre 2021 à 18:41
À : Aayush9029/KenobiSite ***@***.***>
Cc : JC LINDER ***@***.***>, Author ***@***.***>
Objet : Re: [Aayush9029/KenobiSite] No Pairing Code (Issue #5)

 

I've updated the Mac, it should generate proper code :)
https://github.com/Aayush9029/KenobiSite/releases/download/v1.3/Kenobi.app.zip

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Aayush9029** [comment]
Here's our support email:  aayushpokharel36@gmail.com

We'll try to walk you through the pairing process 😅

If you feel like this is too much work. You can apply for the refund [here](https://reportaproblem.apple.com) luckily it's pretty simple process!

> if you end up refunding, We're sorry to see you go! Hopefully you'll come back once our open-source desktop app is stable enough! Also, Here's another app that is similar to kenobi but for iOS: https://apps.apple.com/ca/app/rifi/id1567296199

Have a great week!
